{
 "title": "pg_top_queries",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "vertamedia-clickhouse-datasource"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "select datname from pg.pg_stat_statements where created_hour >=  toStartOfHour(now()-interval 1 hour) group by datname order by datname"
   },
   {
    "name": "hostname",
    "query": "select hostname from pg.pg_stat_statements where datname IN ('$datname') and created_hour >=  toStartOfHour(now()-interval 1 hour) group by hostname order by hostname"
   },
   {
    "name": "column",
    "label": "sort_by",
    "query": "calls,total_time,rows,shared_blks_hit,shared_blks_read,shared_blks_dirtied,shared_blks_written,blk_read_time,blk_write_time,total_time/calls"
   },
   { "name": "limit", "query": "3,5,10,15" },
   { "name": "hide_superuser", "label": "Hide superuser", "query": "no,yes" },
   { "name": "query", "label": "Query Filter" }
  ]
 },
 "panels": [
  {
   "title": "Top $limit by $column Cumulative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Plan of top $limit query by $column",
     "type": "table-old",
     "description": "top $limit по сумме $column за заданный период времени\ntotal_time - общее время выполнения (cpu_time + io_time)\ncalls - количество выполнений\navg_latency - total_time / calls\nbuffers_read - сколько данных в сумме поднял запрос из OS (page cache + disc)",
     "gridPos": { "h": 27, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dateTimeColDataType": "time",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    concat(username, '::', datname, '::', substring(query, 1, 3000)) AS query,\n    SUM(total_time) as total_time,\n    sum(calls) as calls,\n    total_time/calls as avg_latency,\n    8192* SUM(shared_blks_read + temp_blks_read + local_blks_read) AS buffers_read\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND query IN (\n    SELECT concat(username, '::', datname, '::', substring(query, 1, 3000))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY query\n",
       "query": "SELECT\n    concat(username, '::', datname, '::', substring(query, 1, 3000)) AS query,\n    SUM(total_time) as total_time,\n    sum(calls) as calls,\n    total_time/calls as avg_latency,\n    8192* SUM(shared_blks_read + temp_blks_read + local_blks_read) AS buffers_read\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND query IN (\n    SELECT concat(username, '::', datname, '::', substring(query, 1, 3000))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY query\n",
       "rawQuery": "SELECT\n    concat(username, '::', datname, '::', substring(query, 1, 3000)) AS query,\n    SUM(total_time) as total_time,\n    sum(calls) as calls,\n    total_time/calls as avg_latency,\n    8192* SUM(shared_blks_read + temp_blks_read + local_blks_read) AS buffers_read\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020665)) AND(created_date <= toDate(1648024265)))\n    AND((created_at >= 1648020665) AND(created_at <= 1648024265))\n    AND created_hour >= toStartOfHour(toDateTime(1648020665))\n    AND created_hour <= toStartOfHour(toDateTime(1648024265))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND query IN (\n    SELECT concat(username, '::', datname, '::', substring(query, 1, 3000))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020665)) AND(created_date <= toDate(1648024265)))\n        AND((created_at >= 1648020665) AND(created_at <= 1648024265))\n        AND created_hour >= toStartOfHour(toDateTime(1648020665))\n        AND created_hour <= toStartOfHour(toDateTime(1648024265))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY query",
       "round": "0s"
      }
     ]
    }
   ]
  },
  { "title": "detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "total_time",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020680)) AND(created_date <= toDate(1648024280)))\n    AND((created_at >= 1648020680) AND(created_at <= 1648024280))\n    AND created_hour >= toStartOfHour(toDateTime(1648020680))\n    AND created_hour <= toStartOfHour(toDateTime(1648024280))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020680)) AND(created_date <= toDate(1648024280)))\n        AND((created_at >= 1648020680) AND(created_at <= 1648024280))\n        AND created_hour >= toStartOfHour(toDateTime(1648020680))\n        AND created_hour <= toStartOfHour(toDateTime(1648024280))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "calls",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020715)) AND(created_date <= toDate(1648024315)))\n    AND((created_at >= 1648020715) AND(created_at <= 1648024315))\n    AND created_hour >= toStartOfHour(toDateTime(1648020715))\n    AND created_hour <= toStartOfHour(toDateTime(1648024315))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020715)) AND(created_date <= toDate(1648024315)))\n        AND((created_at >= 1648020715) AND(created_at <= 1648024315))\n        AND created_hour >= toStartOfHour(toDateTime(1648020715))\n        AND created_hour <= toStartOfHour(toDateTime(1648024315))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nне учитывает время планирования запроса",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time/calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time/calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(total_time/calls) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020725)) AND(created_date <= toDate(1648024325)))\n    AND((created_at >= 1648020725) AND(created_at <= 1648024325))\n    AND created_hour >= toStartOfHour(toDateTime(1648020725))\n    AND created_hour <= toStartOfHour(toDateTime(1648024325))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020725)) AND(created_date <= toDate(1648024325)))\n        AND((created_at >= 1648020725) AND(created_at <= 1648024325))\n        AND created_hour >= toStartOfHour(toDateTime(1648020725))\n        AND created_hour <= toStartOfHour(toDateTime(1648024325))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "cache hit ratio",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_hit / (shared_blks_hit + shared_blks_read)) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_hit / (shared_blks_hit + shared_blks_read)) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_hit / (shared_blks_hit + shared_blks_read)) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020731)) AND(created_date <= toDate(1648024331)))\n    AND((created_at >= 1648020731) AND(created_at <= 1648024331))\n    AND created_hour >= toStartOfHour(toDateTime(1648020731))\n    AND created_hour <= toStartOfHour(toDateTime(1648024331))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020731)) AND(created_date <= toDate(1648024331)))\n        AND((created_at >= 1648020731) AND(created_at <= 1648024331))\n        AND created_hour >= toStartOfHour(toDateTime(1648020731))\n        AND created_hour <= toStartOfHour(toDateTime(1648024331))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "shared_blks_read",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nTotal number of shared blocks read by the statement * 8192 (block size)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_read * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_read * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(shared_blks_read * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020738)) AND(created_date <= toDate(1648024338)))\n    AND((created_at >= 1648020738) AND(created_at <= 1648024338))\n    AND created_hour >= toStartOfHour(toDateTime(1648020738))\n    AND created_hour <= toStartOfHour(toDateTime(1648024338))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020738)) AND(created_date <= toDate(1648024338)))\n        AND((created_at >= 1648020738) AND(created_at <= 1648024338))\n        AND created_hour >= toStartOfHour(toDateTime(1648020738))\n        AND created_hour <= toStartOfHour(toDateTime(1648024338))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "temp files read and written",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nTotal number of temp blocks read and written by the statement * 8192 (block size)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((temp_blks_read + temp_blks_written) * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((temp_blks_read + temp_blks_written) * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg((temp_blks_read + temp_blks_written) * 8192) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020744)) AND(created_date <= toDate(1648024344)))\n    AND((created_at >= 1648020744) AND(created_at <= 1648024344))\n    AND created_hour >= toStartOfHour(toDateTime(1648020744))\n    AND created_hour <= toStartOfHour(toDateTime(1648024344))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020744)) AND(created_date <= toDate(1648024344)))\n        AND((created_at >= 1648020744) AND(created_at <= 1648024344))\n        AND created_hour >= toStartOfHour(toDateTime(1648020744))\n        AND created_hour <= toStartOfHour(toDateTime(1648024344))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IO time",
   "type": "graph",
   "description": "https://www.postgresql.org/docs/10/pgstatstatements.html\nTotal time spent in the statement, in milliseconds\nper 30 seconds\nTotal time the statement spent writing/reading blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(blk_read_time + blk_write_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "query": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(blk_read_time + blk_write_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n    AND((created_at >= $from) AND(created_at <= $to))\n    AND created_hour >= toStartOfHour(toDateTime($from))\n    AND created_hour <= toStartOfHour(toDateTime($to))\n    AND hostname = '$hostname'\n    AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate($from)) AND(created_date <= toDate($to)))\n        AND((created_at >= $from) AND(created_at <= $to))\n        AND created_hour >= toStartOfHour(toDateTime($from))\n        AND created_hour <= toStartOfHour(toDateTime($to))\n        AND('$query' = '-' OR '$query' = '' OR positionCaseInsensitive(query, '$query') > 0)\n        AND hostname = '$hostname'\n        AND ('$hide_superuser' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum($column) DESC\n    LIMIT $limit)\nGROUP BY t, q\nORDER BY t ASC\n",
     "rawQuery": "SELECT\n    created_at * 1000 AS t,\n    concat(username, '::', datname, '::', substring(query, 1, 500)) AS q,\n    avg(blk_read_time + blk_write_time) as value\nFROM pg.pg_stat_statements\nWHERE\n    ((created_date >= toDate(1648020748)) AND(created_date <= toDate(1648024348)))\n    AND((created_at >= 1648020748) AND(created_at <= 1648024348))\n    AND created_hour >= toStartOfHour(toDateTime(1648020748))\n    AND created_hour <= toStartOfHour(toDateTime(1648024348))\n    AND hostname = 'undefined'\n    AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    AND q IN (\n    SELECT\n      concat(username, '::', datname, '::', substring(query, 1, 500))\n    FROM pg.pg_stat_statements\n    WHERE\n        ((created_date >= toDate(1648020748)) AND(created_date <= toDate(1648024348)))\n        AND((created_at >= 1648020748) AND(created_at <= 1648024348))\n        AND created_hour >= toStartOfHour(toDateTime(1648020748))\n        AND created_hour <= toStartOfHour(toDateTime(1648024348))\n        AND('' = '-' OR '' = '' OR positionCaseInsensitive(query, '') > 0)\n        AND hostname = 'undefined'\n        AND ('yes' = 'no' OR username NOT IN ('postgres','monitor'))\n    GROUP BY\n        username,\n        datname,\n        query\n    ORDER BY sum(total_time) DESC\n    LIMIT 5)\nGROUP BY t, q\nORDER BY t ASC",
     "round": "0s"
    }
   ]
  }
 ]
}